stages:
  - build
  - run

image: node:latest

install:
  stage: build
  tags:
    - task-03-docker
  script:
    - yarn install

test run:
  stage: run
  tags:
    - task-03-docker
  script:
    - yarn start
