stages:
  - build
  - deps
  - test

image: node:latest

build:
  stage: build
  tags:
    - task-03-docker
  script:
    - yarn install

lint test:
  stage: deps
  tags:
    - task-03-docker
  when: on_success
  script:
    - echo "-------------Install dependencies------------"
    - yarn add eslint --dev
    - yarn add eslint-plugin-react --dev

lint test:
  stage: test
  tags:
    - task-03-docker
  when: on_success
  script:
    - echo "----------------Run ES Lint------------------"
    - yarn run eslint ./src/*.js

internal test:
  stage: test
  tags:
    - task-03-docker
  when: on_success
  variables:
    CI: true
  script:
    - yarn test
