stages:
  - build
  - test
  - stage
  - deploy

image: node:latest

arrange:
  stage: build
  tags:
    - task-03-docker
  script:
    - yarn install
    - echo "---------------------------------------------"
    - echo "---          Install dependencies         ---"
    - echo "---------------------------------------------"
    - yarn add eslint --dev
    - yarn add eslint-plugin-react --dev
  artifacts:
    paths:
      - node_modules
  cache:
    key:
      files:
        - yarn.lock
    paths:
      - node_modules

linter_test:
  stage: test
  tags:
    - task-03-docker
  when: on_success
  script:
    - echo "----------------Run ES Lint------------------"
    - yarn run eslint ./src/*.js

yarn_test:
  stage: test
  tags:
    - task-03-docker
  when: on_success
  variables:
    CI: "true"
  script:
    - export
    - yarn test

staging:
  stage: stage
  tags:
    - task-03-docker
  when: on_success
  script:
    - echo "---------------------------------------------"
    - echo "---                Staging                ---"
    - echo "---------------------------------------------"

deploing:
  stage: deploy
  tags:
    - task-03-docker
  when: manual
  script:
    - echo "---------------------------------------------"
    - echo "---               Deploying               ---"
    - echo "---------------------------------------------"
