stages:
  - build
  - test

image: node:latest

build:
  stage: build
  tags:
    - task-03-docker
  script:
    - yarn install

lint test:
  stage: test
  tags:
    - task-03-docker
  script:
    - echo "Running linter_test.sh"
    - yarn add eslint --dev
    - yarn add eslint-plugin-react --dev

internal test:
  stage: test
  tags:
    - task-03-docker
  before_script:
    - CI=true
  script:
    - yarn test
