stages:
  - pretest
  - build
  - test

image: node:latest

lint test:
  stage: pretest
  tags:
    - task-03-docker
  script:
    - echo "Running linter_test.sh"

build:
  stage: build
  tags:
    - task-03-docker
  script:
    - yarn install

internal test:
  stage: test
  tags:
    - task-03-docker
  before_script:
    - CI=true
  script:
    - yarn test
